import socket
from queue import Queue
from typing import Protocol


class InterfaceState(Protocol):
    def setup(self, interface_name: str) -> None: ...

    def listening(self) -> None: ...

    def accept(self) -> None: ...

    def connected(self) -> None: ...

    def receive(self) -> None: ...

    def send_to_interface(self) -> None: ...

    def receive_from_interface(self, data: str) -> None: ...

    def send_to_client(self) -> None: ...

    def close_client(self) -> None: ...


class InterfaceContext(Protocol):
    sock: socket.socket
    input_queue: Queue
    output_queue: Queue

    def set_state(self, state: InterfaceState) -> None: ...

    def setup(self) -> None: ...
